spring:
  jpa:
    defer-datasource-initialization: true
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: example
    driverClassName: org.postgresql.Driver

    