spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: example
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa.hibernate.ddl-auto: create-drop


    